version: '3.8'

services:

  # Spring Boot API
  api:
    build:
      context: SmartHome_API
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    restart: unless-stopped
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/SmartHome?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: password 
    depends_on:
      - db
      # - data_generators
    networks:
      - backend


  # FrontEnd
  frontend:
    build:
      context: SmartHome
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - api
      - db
    networks:
      - frontend


  # Database
  db:
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: SmartHome
      MYSQL_USER: springuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend
      - data_gen


  # Message Queue
  rmq:
    image: rabbitmq:3.11.5-alpine
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/mnesia
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
    environment:
     - RABBITMQ_DEFAULT_PASS=test
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - backend


  # Geração de dados
  data_generators:
    build:
      context: generators
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rmq
      - db
    networks:
      - backend
      - data_gen

  
  # Servidor Python
  server:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8765:8765
    depends_on:
      - db
    networks:
      - frontend
      - data_gen
      

networks: 
  backend:
  frontend:
  data_gen: